name: build test
on: [push]
jobs:
  build_docker:
    name: Builder docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.20.0'
      - run: |
          chmod +x bot-build.sh
          ./bot-build.sh
          go test ./...
